[build]
  # Build command for the frontend
  command = "npm install && npm run build"

  # Directory to publish (frontend build output)
  publish = "dist"

  # Base directory - run commands from ems folder
  base = "ems"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

  # Build environment
  NODE_ENV = "production"

  # NPM configuration
  NPM_FLAGS = "--production=false"

  # Frontend environment variables
  VITE_API_BASE_URL = "https://employee-backend-api.herokuapp.com"
  VITE_ENABLE_DEMO_DATA = "false"
  VITE_DEBUG_MODE = "false"
  VITE_ENABLE_LOGGING = "false"
  VITE_ENABLE_ERROR_BOUNDARY = "true"
  VITE_ENABLE_STATISTICS = "true"

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# API proxy for backend (if needed)
[[redirects]]
  from = "/api/*"
  to = "https://employee-backend-api.herokuapp.com/api/:splat"
  status = 200
  force = true

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
