version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: employee_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: employee_management
      MYSQL_USER: emp_user
      MYSQL_PASSWORD: emp_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database-setup.sql:/docker-entrypoint-initdb.d/database-setup.sql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Uncomment below to run the Spring Boot app in Docker as well
  # employee-app:
  #   build: .
  #   container_name: employee_app
  #   restart: always
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     mysql:
  #       condition: service_healthy
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/employee_management?useSSL=false&serverTimezone=UTC
  #     SPRING_DATASOURCE_USERNAME: root
  #     SPRING_DATASOURCE_PASSWORD: password

volumes:
  mysql_data:
